Output demo.gif

Require echo

Set Theme "Catppuccin Frappe"

Set Shell "bash"
Set FontSize 18
Set Width 1200
Set Height 280

Type@33ms "./instyle '[~italic]you can [~cyan]style[/] text with [~bold+magenta]inStyle[/]!!!'" Sleep 250ms Enter Sleep 2s
Type@33ms "./instyle 'with support for [~#5c7a45+bold]hex[/] codes'" Sleep 250ms Enter Sleep 2s
Type@33ms "./instyle 'and also [~rgb(170,30,150)]rgb[/]!'" Sleep 250ms Enter Sleep 10s
